typography_spectrum: 0.16631
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5587c6'
    - '#ced6e0'
    - '#725f4f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49521
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Sheila Cash
  email: info@sheilacash.com
  url: sheilacash.com
name: evolutionary sparks
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Buy the book
    url: >-
      https://www.amazon.com/Evolve-Your-Life-Conscious-Evolution/dp/1683090004/ref=sr_1_1?ie=UTF8&qid=1472650112&sr=8-1&keywords=evolve+your+life
    type: external
favicon: null
title: evolutionary sparks
description: get life
purpose: []
