name: evolutionary sparks
favicon: null
layout_spectrum: 0.49521
typography_spectrum: 0.16631
title: evolutionary sparks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5587c6'
    - '#ced6e0'
    - '#725f4f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
